import { Mass } from './Mass.js';
import { Speed } from './Speed.js';
import { Power } from './Power.js';
import { TractiveEffort } from './TractiveEffort.js';
import { TrackGauge, TrackGaugeVanilla } from './TrackGauge.js';
import { Role } from './Role.js';
import { Generation } from './Generation.js';
import { GameplayMode } from './GameplayMode.js';
import { Climate } from './Climate.js';


// length is divided into 1/16 units
export const allEngines = [
    {
        name: "4-4-2 Lark (Steam)",
        // units on page use Metric Tonne, not Ton (even though mph and hp are used). wtf
        mass: Mass.Tonne(35),
        maxSpeed: Speed.MilesPerHour(60),
        power: Power.Hp(500),
        te: TractiveEffort.Kn(68),
        length: 0.375,
        gauge: TrackGauge.standard,
        role: Role.GeneralPurposeExpress,
        generation: Generation.first,
        gameplayMode: GameplayMode.simpliflied,
    },
    {
        name: "2-6-2 Merrylegs (Steam)",
        mass: Mass.Tonne(49),
        maxSpeed: Speed.MilesPerHour(75),
        power: Power.Hp(650),
        te: TractiveEffort.Kn(95),
        length: 0.375,
        gauge: TrackGauge.standard,
        role: Role.GeneralPurposeExpress,
        generation: Generation.second,
        gameplayMode: GameplayMode.simpliflied,
    },
    {
        name: "2-6-2 Proper Job (Steam)",
        role: Role.GeneralPurposeExpress,
        generation: Generation.third,
        maxSpeed: Speed.MilesPerHour(90),
        power: Power.Hp(800),
        mass: Mass.Tonne(57),
        gauge: TrackGauge.standard,
        te: TractiveEffort.Kn(111),
        length: 0.375,
        gameplayMode: GameplayMode.simpliflied,
    },
    {
        name: "Kelpie (Diesel)",
        role: Role.GeneralPurposeExpress,
        generation: Generation.fourth,
        maxSpeed: Speed.MilesPerHour(105),
        power: Power.Hp(1450),
        mass: Mass.Tonne(72),
        gauge: TrackGauge.standard,
        te: TractiveEffort.Kn(212),
        length: 0.375,
        gameplayMode: GameplayMode.simpliflied,
    },
    {
        name: "Griffon (Diesel)",
        role: Role.GeneralPurposeExpress,
        generation: Generation.fifth,
        maxSpeed: Speed.MilesPerHour(115),
        power: Power.Hp(1650),
        mass: Mass.Tonne(74),
        gauge: TrackGauge.standard,
        te: TractiveEffort.Kn(218),
        length: 0.375,
        gameplayMode: GameplayMode.simpliflied,
    },

    {
        name: "0-10-0 Decapod (Steam)",
        role: Role.GeneralPurposeExpressJoker,
        generation: Generation.second,
        maxSpeed: Speed.MilesPerHour(75),
        power: Power.Hp(650),
        mass: Mass.Tonne(54),
        gauge: TrackGauge.standard,
        te: TractiveEffort.Kn(105),
        length: 0.375,
        gameplayMode: GameplayMode.full,
    },
    {
        name: "0-6-4 Stag (Steam)",
        role: Role.GeneralPurposeExpressJoker,
        generation: Generation.third,
        maxSpeed: Speed.MilesPerHour(90),
        power: Power.Hp(800),
        mass: Mass.Tonne(60),
        gauge: TrackGauge.standard,
        te: TractiveEffort.Kn(117),
        length: 0.375,
        gameplayMode: GameplayMode.full,
    },
    {
        name: "Foxhound (Diesel)",
        role: Role.GeneralPurposeExpressJoker,
        generation: Generation.fourth,
        maxSpeed: Speed.MilesPerHour(105),
        power: Power.Hp(1450),
        mass: Mass.Tonne(70),
        gauge: TrackGauge.standard,
        te: TractiveEffort.Kn(206),
        length: 0.375,
        gameplayMode: GameplayMode.full,
    },
    {
        name: "Lynx (Diesel)",
        role: Role.GeneralPurposeExpressJoker,
        generation: Generation.fifth,
        maxSpeed: Speed.MilesPerHour(115),
        power: Power.Hp(1650),
        mass: Mass.Tonne(72),
        gauge: TrackGauge.standard,
        te: TractiveEffort.Kn(212),
        length: 0.375,
        gameplayMode: GameplayMode.full,
    },

    {
        name: "Pinhorse (Electric)",
        role: Role.GeneralPurposeExpressJoker,
        generation: Generation.second,
        maxSpeed: Speed.MilesPerHour(75),
        power: Power.Hp(1050),
        mass: Mass.Tonne(60),
        gauge: TrackGauge.electric,
        te: TractiveEffort.Kn(176),
        length: 0.25,
        gameplayMode: GameplayMode.full,
    },
    {
        name: "Argus (Electric)",
        role: Role.GeneralPurposeExpressJoker,
        generation: Generation.third,
        maxSpeed: Speed.MilesPerHour(90),
        power: Power.Hp(1300),
        mass: Mass.Tonne(67),
        gauge: TrackGauge.electric,
        te: TractiveEffort.Kn(197),
        length: 0.25,
        gameplayMode: GameplayMode.full,
    },
    {
        name: "Booster (Electric)",
        role: Role.GeneralPurposeExpressJoker,
        generation: Generation.fourth,
        maxSpeed: Speed.MilesPerHour(105),
        power: Power.Hp(1600),
        mass: Mass.Tonne(70),
        gauge: TrackGauge.electric,
        te: TractiveEffort.Kn(206),
        length: 0.375,
        gameplayMode: GameplayMode.full,
    },
    {
        name: "Booster (Diesel)",
        role: Role.GeneralPurposeExpressJoker,
        generation: Generation.fourth,
        maxSpeed: Speed.MilesPerHour(105),
        power: Power.Hp(600),
        mass: Mass.Tonne(70),
        gauge: TrackGauge.standard,
        te: TractiveEffort.Kn(206),
        length: 0.375,
        gameplayMode: GameplayMode.full,
    },
    {
        name: "Tornado (Electric)",
        role: Role.GeneralPurposeExpressJoker,
        generation: Generation.fifth,
        maxSpeed: Speed.MilesPerHour(115),
        power: Power.Hp(1900),
        mass: Mass.Tonne(70),
        gauge: TrackGauge.electric,
        te: TractiveEffort.Kn(206),
        length: 0.375,
        gameplayMode: GameplayMode.full,
    },
    {
        name: "Tornado (Diesel)",
        role: Role.GeneralPurposeExpressJoker,
        generation: Generation.fifth,
        maxSpeed: Speed.MilesPerHour(115),
        power: Power.Hp(750),
        mass: Mass.Tonne(70),
        gauge: TrackGauge.standard,
        te: TractiveEffort.Kn(206),
        length: 0.375,
        gameplayMode: GameplayMode.full,
    },

    {
        name: "4-2-2 Spinner (Steam)",
        mass: Mass.Tonne(78),
        maxSpeed: Speed.MilesPerHour(60),
        power: Power.Hp(950),
        te: TractiveEffort.Kn(92),
        length: 0.5,
        gauge: TrackGauge.standard,
        role: Role.Express,
        generation: Generation.first,
        gameplayMode: GameplayMode.simpliflied,
    },
    {
        name: "4-4-0 Carrack (Steam)",
        role: Role.GeneralPurposeExpress,
        generation: Generation.second,
        maxSpeed: Speed.MilesPerHour(75),
        power: Power.Hp(1150),
        mass: Mass.Tonne(90),
        gauge: TrackGauge.standard,
        te: TractiveEffort.Kn(158),
        length: 0.5,
        gameplayMode: GameplayMode.simpliflied,
    },
    {
        name: "4-4-0 Tencendur (Steam)",
        role: Role.GeneralPurposeExpress,
        generation: Generation.third,
        maxSpeed: Speed.MilesPerHour(90),
        power: Power.Hp(1400),
        mass: Mass.Tonne(110),
        gauge: TrackGauge.standard,
        te: TractiveEffort.Kn(193),
        length: 0.5,
        gameplayMode: GameplayMode.simpliflied,
    },
    {
        name: "Daring (Diesel)",
        role: Role.GeneralPurposeExpress,
        generation: Generation.fourth,
        maxSpeed: Speed.MilesPerHour(105),
        power: Power.Hp(1750),
        mass: Mass.Tonne(75),
        gauge: TrackGauge.standard,
        te: TractiveEffort.Kn(221),
        length: 0.5,
        gameplayMode: GameplayMode.simpliflied,
    },
    {
        name: "Shredder (Diesel)",
        role: Role.GeneralPurposeExpress,
        generation: Generation.fifth,
        maxSpeed: Speed.MilesPerHour(125),
        power: Power.Hp(2100),
        mass: Mass.Tonne(76),
        gauge: TrackGauge.standard,
        te: TractiveEffort.Kn(224),
        length: 0.5,
        gameplayMode: GameplayMode.simpliflied,
    },

    {
        name: "2-4-0 Reliance (Steam)",
        role: Role.GeneralPurposeExpressJoker,
        generation: Generation.first,
        maxSpeed: Speed.MilesPerHour(60),
        power: Power.Hp(950),
        mass: Mass.Tonne(86),
        gauge: TrackGauge.standard,
        te: TractiveEffort.Kn(102),
        length: 0.5, // replaced by Carrack
        gameplayMode: GameplayMode.full,
    },
    {
        name: "Shoebox (Electro)",
        role: Role.GeneralPurposeExpressJoker,
        generation: Generation.fourth,
        maxSpeed: Speed.MilesPerHour(105),
        power: Power.Hp(2300),
        mass: Mass.Tonne(86),
        gauge: TrackGauge.electric,
        te: TractiveEffort.Kn(197),
        length: 0.5,
        gameplayMode: GameplayMode.full,
    },
    {
        name: "Shoebox (Diesel)",
        role: Role.GeneralPurposeExpressJoker,
        generation: Generation.fourth,
        maxSpeed: Speed.MilesPerHour(105),
        power: Power.Hp(950),
        mass: Mass.Tonne(86),
        gauge: TrackGauge.standard,
        te: TractiveEffort.Kn(197),
        length: 0.5,
        gameplayMode: GameplayMode.full,
    },
    {
        name: "Super Shoebox (Electric)",
        role: Role.GeneralPurposeExpressJoker,
        generation: Generation.fifth,
        maxSpeed: Speed.MilesPerHour(115),
        power: Power.Hp(2600),
        mass: Mass.Tonne(73),
        gauge: TrackGauge.electric,
        te: TractiveEffort.Kn(212),
        length: 0.5,
        gameplayMode: GameplayMode.full,
    },
    {
        name: "Super Shoebox (Diesel)",
        role: Role.GeneralPurposeExpressJoker,
        generation: Generation.fifth,
        maxSpeed: Speed.MilesPerHour(115),
        power: Power.Hp(1250),
        mass: Mass.Tonne(73),
        gauge: TrackGauge.standard,
        te: TractiveEffort.Kn(212),
        length: 0.5,
        gameplayMode: GameplayMode.full,
    },
    {
        name: "Ultra Shoebox (Electric)",
        role: Role.GeneralPurposeExpressJoker,
        generation: Generation.sixth,
        maxSpeed: Speed.MilesPerHour(125),
        power: Power.Hp(2800),
        mass: Mass.Tonne(70),
        gauge: TrackGauge.electric,
        te: TractiveEffort.Kn(229),
        length: 0.5,
        gameplayMode: GameplayMode.full,
    },
    {
        name: "Ultra Shoebox (Diesel)",
        role: Role.GeneralPurposeExpressJoker,
        generation: Generation.sixth,
        maxSpeed: Speed.MilesPerHour(125),
        power: Power.Hp(1650),
        mass: Mass.Tonne(70),
        gauge: TrackGauge.standard,
        te: TractiveEffort.Kn(229),
        length: 0.5,
        gameplayMode: GameplayMode.full,
    },


    {
        name: "4-4-2 Swift (Steam)",
        role: Role.HeavyGeneralPurposeExpress,
        generation: Generation.second,
        maxSpeed: Speed.MilesPerHour(75),
        power: Power.Hp(1550),
        mass: Mass.Tonne(115),
        gauge: TrackGauge.standard,
        te: TractiveEffort.Kn(202),
        length: 0.625,
        gameplayMode: GameplayMode.simpliflied,
    },
    {
        name: "4-6-0 Strongbow (Steam)",
        role: Role.HeavyGeneralPurposeExpress,
        generation: Generation.third,
        maxSpeed: Speed.MilesPerHour(90),
        power: Power.Hp(1900),
        mass: Mass.Tonne(130),
        gauge: TrackGauge.standard,
        te: TractiveEffort.Kn(228),
        length: 0.625,
        gameplayMode: GameplayMode.simpliflied,
    },
    {
        name: "Wyvern (Diesel)",
        role: Role.HeavyGeneralPurposeExpress,
        generation: Generation.fourth,
        maxSpeed: Speed.MilesPerHour(105),
        power: Power.Hp(2200),
        mass: Mass.Tonne(130),
        gauge: TrackGauge.standard,
        te: TractiveEffort.Kn(383),
        length: 0.5,
        gameplayMode: GameplayMode.simpliflied,
    },
    {
        name: "Revolution (Diesel)",
        role: Role.HeavyGeneralPurposeExpress,
        generation: Generation.sixth,
        maxSpeed: Speed.MilesPerHour(125),
        power: Power.Hp(2950),
        mass: Mass.Tonne(95),
        gauge: TrackGauge.electric,
        te: TractiveEffort.Kn(280),
        length: 0.5,
        gameplayMode: GameplayMode.simpliflied,
    },
    {
        name: "Revolution (Electro)",
        role: Role.HeavyGeneralPurposeExpress,
        generation: Generation.sixth,
        maxSpeed: Speed.MilesPerHour(125),
        power: Power.Hp(4200),
        mass: Mass.Tonne(95),
        gauge: TrackGauge.standard,
        te: TractiveEffort.Kn(280),
        length: 0.5,
        gameplayMode: GameplayMode.simpliflied,
    },

    {
        name: "4-6-0 Thunderer (Steam)",
        role: Role.HeavyGeneralPurposeExpressJoker,
        generation: Generation.second,
        maxSpeed: Speed.MilesPerHour(75),
        power: Power.Hp(1500),
        mass: Mass.Tonne(112),
        gauge: TrackGauge.standard,
        te: TractiveEffort.Kn(218),
        length: 0.625, // replaced by Tenacious
        gameplayMode: GameplayMode.full,
    },
    {
        name: "Tenacious (Diesel)",
        role: Role.HeavyGeneralPurposeExpressJoker,
        generation: Generation.fourth,
        maxSpeed: Speed.MilesPerHour(105),
        power: Power.Hp(2150),
        mass: Mass.Tonne(80),
        gauge: TrackGauge.standard,
        te: TractiveEffort.Kn(235),
        length: 0.5,
        gameplayMode: GameplayMode.full,
    },
    {
        name: "Resilient (Diesel)",
        role: Role.HeavyGeneralPurposeExpressJoker,
        generation: Generation.fifth,
        maxSpeed: Speed.MilesPerHour(115),
        power: Power.Hp(2750),
        mass: Mass.Tonne(112),
        gauge: TrackGauge.standard,
        te: TractiveEffort.Kn(330),
        length: 0.5,
        gameplayMode: GameplayMode.full,
    },

    {
        name: "2-6-2 Arrow (Steam)",
        role: Role.HeavyGeneralPurposeExpressJoker,
        generation: Generation.third,
        maxSpeed: Speed.MilesPerHour(90),
        power: Power.Hp(1900),
        mass: Mass.Tonne(140),
        gauge: TrackGauge.standard,
        te: TractiveEffort.Kn(383),
        length: 0.625,
        gameplayMode: GameplayMode.full,
    },
    {
        name: "Intrepid (Diesel)",
        role: Role.HeavyGeneralPurposeExpressJoker,
        generation: Generation.fourth,
        maxSpeed: Speed.MilesPerHour(105),
        power: Power.Hp(2200),
        mass: Mass.Tonne(115),
        gauge: TrackGauge.standard,
        te: TractiveEffort.Kn(338),
        length: 0.5,
        gameplayMode: GameplayMode.full,
    },

    {
        name: "2-8-2 Pegasus (Steam)",
        role: Role.HeavyGeneralPurposeExpress,
        generation: Generation.third,
        maxSpeed: Speed.MilesPerHour(90),
        power: Power.Hp(2300),
        mass: Mass.Tonne(150),
        gauge: TrackGauge.standard,
        te: TractiveEffort.Kn(367),
        length: 0.75,
        gameplayMode: GameplayMode.simpliflied,
    },
    {
        name: "Dragon (Diesel)",
        role: Role.HeavyGeneralPurposeExpress,
        generation: Generation.fourth,
        maxSpeed: Speed.MilesPerHour(105),
        power: Power.Hp(2750),
        mass: Mass.Tonne(99),
        gauge: TrackGauge.standard,
        te: TractiveEffort.Kn(291),
        length: 0.5,
        gameplayMode: GameplayMode.simpliflied,
    },
    {
        name: "Onslaught (Diesel)",
        role: Role.HeavyGeneralPurposeExpress,
        generation: Generation.fifth,
        maxSpeed: Speed.MilesPerHour(125),
        power: Power.Hp(3300),
        mass: Mass.Tonne(100),
        gauge: TrackGauge.standard,
        te: TractiveEffort.Kn(294),
        length: 0.5,
        gameplayMode: GameplayMode.simpliflied,
    },

    {
        name: "4-8-2 Hawkinge (Diesel)",
        role: Role.GeneralPurposeExpress,
        generation: Generation.third,
        maxSpeed: Speed.MilesPerHour(90),
        power: Power.Hp(2350),
        mass: Mass.Tonne(156),
        gauge: TrackGauge.standard,
        te: TractiveEffort.Kn(382),
        length: 0.5,
        gameplayMode: GameplayMode.full,
    },
    {
        name: "Falcon (Diesel)",
        role: Role.GeneralPurposeExpress,
        generation: Generation.fourth,
        maxSpeed: Speed.MilesPerHour(105),
        power: Power.Hp(2800),
        mass: Mass.Tonne(115),
        gauge: TrackGauge.standard,
        te: TractiveEffort.Kn(338),
        length: 0.5, // replaced by Onslaught
        gameplayMode: GameplayMode.full,
    },
    {
        name: "Relentless (Diesel)",
        role: Role.HeavyGeneralPurposeExpress,
        generation: Generation.sixth,
        maxSpeed: Speed.MilesPerHour(125),
        power: Power.Hp(4250),
        mass: Mass.Tonne(95),
        gauge: TrackGauge.standard,
        te: TractiveEffort.Kn(280),
        length: 0.5,
        gameplayMode: GameplayMode.full,
    },

    {
        name: "4-6-4 Streamer (Steam)",
        role: Role.HeavyGeneralPurposeExpressJoker,
        generation: Generation.third,
        maxSpeed: Speed.MilesPerHour(90),
        power: Power.Hp(2300),
        mass: Mass.Tonne(150),
        gauge: TrackGauge.standard,
        te: TractiveEffort.Kn(213),
        length: 0.625,
        gameplayMode: GameplayMode.full,
    },
    {
        name: "Vulcan (Diesel)",
        role: Role.HeavyGeneralPurposeExpressJoker,
        generation: Generation.fourth,
        maxSpeed: Speed.MilesPerHour(105),
        power: Power.Hp(2750),
        mass: Mass.Tonne(105),
        gauge: TrackGauge.standard,
        te: TractiveEffort.Kn(309),
        length: 0.5,
        gameplayMode: GameplayMode.full,
    },
    {
        name: "Dreadnought (Diesel)",
        role: Role.HeavyGeneralPurposeExpressJoker,
        generation: Generation.fifth,
        maxSpeed: Speed.MilesPerHour(125),
        power: Power.Hp(3300),
        mass: Mass.Tonne(102),
        gauge: TrackGauge.standard,
        te: TractiveEffort.Kn(300),
        length: 0.5,
        gameplayMode: GameplayMode.full,
    },

    {
        name: "Hurly Burly (Electric)",
        role: Role.SuperHeavyGeneralPurposeExpress,
        generation: Generation.second,
        maxSpeed: Speed.MilesPerHour(75),
        power: Power.Hp(1800),
        mass: Mass.Tonne(90),
        gauge: TrackGauge.electric,
        te: TractiveEffort.Kn(220),
        length: 0.5,
        gameplayMode: GameplayMode.simpliflied,
    },
    {
        name: "Moor Gallop (Electric)",
        role: Role.SuperHeavyGeneralPurposeExpress,
        generation: Generation.third,
        maxSpeed: Speed.MilesPerHour(90),
        power: Power.Hp(2400),
        mass: Mass.Tonne(105),
        gauge: TrackGauge.electric,
        te: TractiveEffort.Kn(257),
        length: 0.5,
        gameplayMode: GameplayMode.simpliflied,
    },
    {
        name: "Roarer (Electric)",
        role: Role.SuperHeavyGeneralPurposeExpress,
        generation: Generation.fourth,
        maxSpeed: Speed.MilesPerHour(105),
        power: Power.Hp(3000),
        mass: Mass.Tonne(80),
        gauge: TrackGauge.electric,
        te: TractiveEffort.Kn(235),
        length: 0.5,
        gameplayMode: GameplayMode.simpliflied,
    },
    {
        name: "Fury (Electric)",
        role: Role.SuperHeavyGeneralPurposeExpress,
        generation: Generation.fifth,
        maxSpeed: Speed.MilesPerHour(115),
        power: Power.Hp(3600),
        mass: Mass.Tonne(82),
        gauge: TrackGauge.electric,
        te: TractiveEffort.Kn(241),
        length: 0.5,
        gameplayMode: GameplayMode.simpliflied,
    },

    {
        name: "Zebedee (Electric)",
        role: Role.SuperHeavyGeneralPurposeExpressJoker,
        generation: Generation.fourth,
        maxSpeed: Speed.MilesPerHour(105),
        power: Power.Hp(4000),
        mass: Mass.Tonne(82),
        gauge: TrackGauge.electric,
        te: TractiveEffort.Kn(241),
        length: 0.5,
        gameplayMode: GameplayMode.full,
    },
    {
        name: "Screamer (Electric)",
        role: Role.SuperHeavyGeneralPurposeExpressJoker,
        generation: Generation.fifth,
        maxSpeed: Speed.MilesPerHour(115),
        power: Power.Hp(4800),
        mass: Mass.Tonne(85),
        gauge: TrackGauge.electric,
        te: TractiveEffort.Kn(250),
        length: 0.5,
        gameplayMode: GameplayMode.full,
    },

    {
        name: "Avenger (Electric)",
        role: Role.UltraHeavyGeneralPurposeExpress,
        generation: Generation.fifth,
        maxSpeed: Speed.MilesPerHour(125),
        power: Power.Hp(5800),
        mass: Mass.Tonne(100),
        gauge: TrackGauge.electric,
        te: TractiveEffort.Kn(294),
        length: 0.5,
        gameplayMode: GameplayMode.simpliflied,
    },

    {
        name: "Sizzler (Electric)",
        role: Role.UltraHeavyGeneralPurposeExpress,
        generation: Generation.sixth,
        maxSpeed: Speed.MilesPerHour(125),
        power: Power.Hp(6600),
        mass: Mass.Tonne(82),
        gauge: TrackGauge.electric,
        te: TractiveEffort.Kn(241),
        length: 0.5,
        gameplayMode: GameplayMode.simpliflied,
    },

    {
        name: "0-8-0 Saxon (Steam)",
        role: Role.Freight,
        generation: Generation.third,
        maxSpeed: Speed.MilesPerHour(60),
        power: Power.Hp(1000),
        mass: Mass.Tonne(65),
        gauge: TrackGauge.standard,
        te: TractiveEffort.Kn(238),
        length: 0.375,
        gameplayMode: GameplayMode.simpliflied,
    },
    {
        name: "Little Bear (Diesel)",
        role: Role.Freight,
        generation: Generation.fourth,
        maxSpeed: Speed.MilesPerHour(75),
        power: Power.Hp(1150),
        mass: Mass.Tonne(68),
        gauge: TrackGauge.standard,
        te: TractiveEffort.Kn(249),
        length: 0.375,
        gameplayMode: GameplayMode.simpliflied,
    },
    {
        name: "Goliath (Diesel)",
        role: Role.Freight,
        generation: Generation.fifth,
        maxSpeed: Speed.MilesPerHour(87),
        power: Power.Hp(1300),
        mass: Mass.Tonne(71),
        gauge: TrackGauge.standard,
        te: TractiveEffort.Kn(260),
        length: 0.375,
        gameplayMode: GameplayMode.simpliflied,
    },

    {
        name: "0-6-2 Buffalo (Steam)",
        role: Role.FreightJoker,
        generation: Generation.first,
        maxSpeed: Speed.MilesPerHour(45),
        power: Power.Hp(650),
        mass: Mass.Tonne(46),
        gauge: TrackGauge.standard,
        te: TractiveEffort.Kn(135),
        length: 0.375, // replaced by Saxon
        gameplayMode: GameplayMode.full,
    },
    {
        name: "Captain Steel (Diesel)",
        role: Role.Freight,
        generation: Generation.fourth,
        maxSpeed: Speed.MilesPerHour(75),
        power: Power.Hp(1150),
        mass: Mass.Tonne(70),
        gauge: TrackGauge.standard,
        te: TractiveEffort.Kn(257),
        length: 0.375,
        gameplayMode: GameplayMode.full,
    },

    {
        name: "Stoat (Electric)",
        role: Role.Freight,
        generation: Generation.second,
        maxSpeed: Speed.MilesPerHour(60),
        power: Power.Hp(1050),
        mass: Mass.Tonne(54),
        gauge: TrackGauge.electric,
        te: TractiveEffort.Kn(159),
        length: 0.375,
        gameplayMode: GameplayMode.simpliflied,
    },
    {
        name: "Stoat (Electric)",
        role: Role.Freight,
        generation: Generation.third,
        maxSpeed: Speed.MilesPerHour(60),
        power: Power.Hp(1050),
        mass: Mass.Tonne(54),
        gauge: TrackGauge.electric,
        te: TractiveEffort.Kn(159),
        length: 0.375,
        gameplayMode: GameplayMode.simpliflied,
    },
    {
        name: "Zest (Electric)",
        role: Role.Freight,
        generation: Generation.fourth,
        maxSpeed: Speed.MilesPerHour(87),
        power: Power.Hp(1600),
        mass: Mass.Tonne(54),
        gauge: TrackGauge.electric,
        te: TractiveEffort.Kn(159),
        length: 0.5,
        gameplayMode: GameplayMode.simpliflied,
    },

    {
        name: "0-6-0 Hercules (Steam)",
        role: Role.Freight,
        generation: Generation.first,
        maxSpeed: Speed.MilesPerHour(45),
        power: Power.Hp(1100),
        mass: Mass.Tonne(89),
        gauge: TrackGauge.standard,
        te: TractiveEffort.Kn(207),
        length: 0.5,
        gameplayMode: GameplayMode.simpliflied,
    },
    {
        name: "2-6-0 Braf (Steam)",
        role: Role.Freight,
        generation: Generation.second,
        maxSpeed: Speed.MilesPerHour(45),
        power: Power.Hp(1250),
        mass: Mass.Tonne(98),
        gauge: TrackGauge.standard,
        te: TractiveEffort.Kn(228),
        length: 0.5,
        gameplayMode: GameplayMode.simpliflied,
    },
    {
        name: "2-6-0 Diablo (Steam)",
        role: Role.Freight,
        generation: Generation.third,
        maxSpeed: Speed.MilesPerHour(75),
        power: Power.Hp(1500),
        mass: Mass.Tonne(106),
        gauge: TrackGauge.standard,
        te: TractiveEffort.Kn(227),
        length: 0.5,
        gameplayMode: GameplayMode.full,
    },


    {
        name: "0-8-0 Eastern (Steam)",
        role: Role.FreightJoker,
        generation: Generation.second,
        maxSpeed: Speed.MilesPerHour(45),
        power: Power.Hp(1250),
        mass: Mass.Tonne(100),
        gauge: TrackGauge.standard,
        te: TractiveEffort.Kn(264),
        length: 0.5,
        gameplayMode: GameplayMode.full,
    },
    {
        name: "0-8-0 Haar (Steam)",
        role: Role.Freight,
        generation: Generation.third,
        maxSpeed: Speed.MilesPerHour(60),
        power: Power.Hp(1500),
        mass: Mass.Tonne(110),
        gauge: TrackGauge.standard,
        te: TractiveEffort.Kn(256),
        length: 0.5,
        gameplayMode: GameplayMode.simpliflied,
    },
    {
        name: "Growler (Diesel)",
        role: Role.Freight,
        generation: Generation.fourth,
        maxSpeed: Speed.MilesPerHour(75),
        power: Power.Hp(1750),
        mass: Mass.Tonne(100),
        gauge: TrackGauge.standard,
        te: TractiveEffort.Kn(294),
        length: 0.5,
        gameplayMode: GameplayMode.simpliflied,
    },
    {
        name: "Slug (Diesel)",
        role: Role.Freight,
        generation: Generation.fifth,
        maxSpeed: Speed.MilesPerHour(87),
        power: Power.Hp(1950),
        mass: Mass.Tonne(110),
        gauge: TrackGauge.standard,
        te: TractiveEffort.Kn(324),
        length: 0.5,
        gameplayMode: GameplayMode.simpliflied,
    },

    {
        name: "2-6-0 Diablo (Steam)",
        role: Role.Freight,
        generation: Generation.third,
        maxSpeed: Speed.MilesPerHour(75),
        power: Power.Hp(1500),
        mass: Mass.Tonne(106),
        gauge: TrackGauge.standard,
        te: TractiveEffort.Kn(227),
        length: 0.5,
        gameplayMode: GameplayMode.full,
    },
    {
        name: "Merlion (Diesel)",
        role: Role.GeneralPurposeExpress,
        generation: Generation.fourth,
        maxSpeed: Speed.MilesPerHour(105),
        power: Power.Hp(1750),
        mass: Mass.Tonne(105),
        gauge: TrackGauge.standard,
        te: TractiveEffort.Kn(265),
        length: 0.5,
        gameplayMode: GameplayMode.full,
    },
    {
        name: "Viking (Diesel)",
        role: Role.FreightJoker,
        generation: Generation.fifth,
        maxSpeed: Speed.MilesPerHour(87),
        power: Power.Hp(1950),
        mass: Mass.Tonne(95),
        gauge: TrackGauge.standard,
        te: TractiveEffort.Kn(280),
        length: 0.5,
        gameplayMode: GameplayMode.full,
    },

    {
        name: "0-6-0+0-6-0 Xeres (Steam)",
        role: Role.HeavyFreight,
        generation: Generation.first,
        maxSpeed: Speed.MilesPerHour(45),
        power: Power.Hp(1450),
        mass: Mass.Tonne(98),
        gauge: TrackGauge.standard,
        te: TractiveEffort.Kn(288),
        length: 0.625,
        gameplayMode: GameplayMode.simpliflied,
    },
    {
        name: "0-6-0+0-6-0 Xeres (Steam)",
        role: Role.HeavyFreight,
        generation: Generation.second,
        maxSpeed: Speed.MilesPerHour(45),
        power: Power.Hp(1450),
        mass: Mass.Tonne(98),
        gauge: TrackGauge.standard,
        te: TractiveEffort.Kn(288),
        length: 0.625,
        gameplayMode: GameplayMode.simpliflied,
    },
    {
        name: "2-8-0 Mainstay (Steam)",
        role: Role.HeavyFreight,
        generation: Generation.third,
        maxSpeed: Speed.MilesPerHour(60),
        power: Power.Hp(1850),
        mass: Mass.Tonne(145),
        gauge: TrackGauge.standard,
        te: TractiveEffort.Kn(329),
        length: 0.625,
        gameplayMode: GameplayMode.simpliflied,
    },
    {
        name: "Yillen (Diesel)",
        role: Role.HeavyFreight,
        generation: Generation.fourth,
        maxSpeed: Speed.MilesPerHour(75),
        power: Power.Hp(2200),
        mass: Mass.Tonne(140),
        gauge: TrackGauge.standard,
        te: TractiveEffort.Kn(412),
        length: 0.625,
        gameplayMode: GameplayMode.simpliflied,
    },
    {
        name: "Doubletide (Diesel)",
        role: Role.HeavyFreight,
        generation: Generation.fifth,
        maxSpeed: Speed.MilesPerHour(87),
        power: Power.Hp(2500),
        mass: Mass.Tonne(136),
        gauge: TrackGauge.standard,
        te: TractiveEffort.Kn(400),
        length: 0.625,
        gameplayMode: GameplayMode.simpliflied,
    },

    {
        name: "Quietus (Diesel)",
        generation: Generation.sixth,
        maxSpeed: Speed.MilesPerHour(87),
        power: Power.Hp(3250),
        mass: Mass.Tonne(136),
        te: TractiveEffort.Kn(499),
        length: 0.5,
        gauge: TrackGauge.standard,
        role: Role.HeavyFreightJoker,
        gameplayMode: GameplayMode.full,
    },
    {
        name: "Quietus (Electric)",
        generation: Generation.sixth,
        maxSpeed: Speed.MilesPerHour(87),
        power: Power.Hp(6700),
        mass: Mass.Tonne(136),
        te: TractiveEffort.Kn(499),
        length: 0.5,
        gauge: TrackGauge.electric,
        role: Role.HeavyFreightJoker,
        gameplayMode: GameplayMode.full,
    },

    {
        name: "2-8-0 Vigilant (Steam)",
        role: Role.HeavyFreight,
        generation: Generation.second,
        maxSpeed: Speed.MilesPerHour(45),
        power: Power.Hp(1850),
        mass: Mass.Tonne(132),
        gauge: TrackGauge.standard,
        te: TractiveEffort.Kn(414),
        length: 0.625,
        gameplayMode: GameplayMode.simpliflied,
    },
    {
        name: "4-8-0 Lemon (Steam)",
        role: Role.HeavyFreight,
        generation: Generation.third,
        maxSpeed: Speed.MilesPerHour(75),
        power: Power.Hp(2400),
        mass: Mass.Tonne(165),
        gauge: TrackGauge.standard,
        te: TractiveEffort.Kn(467),
        length: 0.75,
        gameplayMode: GameplayMode.simpliflied,
    },
    {
        name: "Chinook (Diesel)",
        role: Role.HeavyFreight,
        generation: Generation.fourth,
        maxSpeed: Speed.MilesPerHour(75),
        power: Power.Hp(2900),
        mass: Mass.Tonne(160),
        gauge: TrackGauge.standard,
        te: TractiveEffort.Kn(471),
        length: 0.75,
        gameplayMode: GameplayMode.simpliflied,
    },
    {
        name: "Grid (Diesel)",
        role: Role.HeavyFreight,
        generation: Generation.fifth,
        maxSpeed: Speed.MilesPerHour(87),
        power: Power.Hp(3300),
        mass: Mass.Tonne(120),
        gauge: TrackGauge.standard,
        te: TractiveEffort.Kn(353),
        length: 0.5,
        gameplayMode: GameplayMode.simpliflied,
    },
    {
        name: "Blackthorn (Diesel)",
        role: Role.HeavyFreight,
        generation: Generation.sixth,
        maxSpeed: Speed.MilesPerHour(87),
        power: Power.Hp(3650),
        mass: Mass.Tonne(124),
        gauge: TrackGauge.standard,
        te: TractiveEffort.Kn(365),
        length: 0.5,
        gameplayMode: GameplayMode.simpliflied,
    },

    {
        name: "0-10-0 Girt Licker (Steam)",
        generation: Generation.second,
        maxSpeed: Speed.MilesPerHour(45),
        power: Power.Hp(1850),
        mass: Mass.Tonne(145),
        gauge: TrackGauge.standard,
        te: TractiveEffort.Kn(466),
        length: 0.625,
        role: Role.HeavyFreightJoker,
        gameplayMode: GameplayMode.full,
    },
    {
        name: "2-6-0+0-6-2 Esk (Steam)",
        generation: Generation.third,
        maxSpeed: Speed.MilesPerHour(60),
        power: Power.Hp(2400),
        mass: Mass.Tonne(180),
        te: TractiveEffort.Kn(702),
        length: 0.75,
        gauge: TrackGauge.standard,
        role: Role.HeavyFreightJoker,
        gameplayMode: GameplayMode.full,
    },
    {
        name: "Withershins (Diesel)",
        role: Role.Freight,
        generation: Generation.fourth,
        maxSpeed: Speed.MilesPerHour(75),
        power: Power.Hp(2900),
        mass: Mass.Tonne(164),
        te: TractiveEffort.Kn(483),
        length: 0.75,
        gauge: TrackGauge.standard,
        gameplayMode: GameplayMode.full,
    },
    {
        name: "Bone (Diesel)",
        generation: Generation.fifth,
        maxSpeed: Speed.MilesPerHour(87),
        power: Power.Hp(3300),
        mass: Mass.Tonne(125),
        te: TractiveEffort.Kn(368),
        length: 0.5,
        gauge: TrackGauge.standard,
        role: Role.HeavyFreightJoker,
        gameplayMode: GameplayMode.full,
    },
    {
        name: "Defiant (Diesel)",
        generation: Generation.sixth,
        maxSpeed: Speed.MilesPerHour(87),
        power: Power.Hp(4150),
        mass: Mass.Tonne(100),
        te: TractiveEffort.Kn(348),
        length: 0.5,
        gauge: TrackGauge.standard,
        role: Role.GeneralPurpose,
        gameplayMode: GameplayMode.full,
    },

    {
        name: "Cheddar Valley (Diesel)",
        role: Role.SuperHeavyFreight,
        generation: Generation.fifth,
        maxSpeed: Speed.MilesPerHour(87),
        power: Power.Hp(4050),
        mass: Mass.Tonne(125),
        gauge: TrackGauge.standard,
        te: TractiveEffort.Kn(488),
        length: 0.5,
        gameplayMode: GameplayMode.simpliflied,
    },

    {
        name: "Stentor (Diesel)",
        role: Role.SuperHeavyFreightJoker,
        generation: Generation.fifth,
        maxSpeed: Speed.MilesPerHour(87),
        power: Power.Hp(4050),
        mass: Mass.Tonne(128),
        gauge: TrackGauge.standard,
        te: TractiveEffort.Kn(499),
        length: 0.5,
        gameplayMode: GameplayMode.full,
    },

    {
        name: "Toaster (Diesel)",
        generation: Generation.sixth,
        maxSpeed: Speed.MilesPerHour(87),
        power: Power.Hp(4550),
        mass: Mass.Tonne(130),
        te: TractiveEffort.Kn(507),
        length: 0.5,
        gauge: TrackGauge.standard,
        role: Role.SuperHeavyFreightJoker,
        gameplayMode: GameplayMode.full,
    },

    {
        name: "Flindermouse (Electric)",
        role: Role.UltraHeavyFreight,
        generation: Generation.second,
        maxSpeed: Speed.MilesPerHour(60),
        power: Power.Hp(2500),
        mass: Mass.Tonne(130),
        gauge: TrackGauge.electric,
        te: TractiveEffort.Kn(383),
        length: 0.5,
        gameplayMode: GameplayMode.simpliflied,
    },
    {
        name: "Flindermouse (Electric)",
        role: Role.UltraHeavyFreight,
        generation: Generation.third,
        maxSpeed: Speed.MilesPerHour(60),
        power: Power.Hp(2500),
        mass: Mass.Tonne(130),
        gauge: TrackGauge.electric,
        te: TractiveEffort.Kn(383),
        length: 0.5,
        gameplayMode: GameplayMode.simpliflied,
    },
    {
        name: "Peasweep (Electric)",
        role: Role.UltraHeavyFreight,
        generation: Generation.fourth,
        maxSpeed: Speed.MilesPerHour(75),
        power: Power.Hp(3700),
        mass: Mass.Tonne(150),
        gauge: TrackGauge.electric,
        te: TractiveEffort.Kn(442),
        length: 0.75,
        gameplayMode: GameplayMode.simpliflied,
    },
    {
        name: "Flanders Storm (Electric)",
        role: Role.UltraHeavyFreight,
        generation: Generation.fifth,
        maxSpeed: Speed.MilesPerHour(87),
        power: Power.Hp(5800),
        mass: Mass.Tonne(120),
        gauge: TrackGauge.electric,
        te: TractiveEffort.Kn(468),
        length: 0.5,
        gameplayMode: GameplayMode.simpliflied,
    },

    {
        name: "2-6-2 Cheese Bug (Steam)",
        mass: Mass.Tonne(16),
        maxSpeed: Speed.MilesPerHour(45),
        power: Power.Hp(300),
        te: TractiveEffort.Kn(31),
        length: 0.25,
        gauge: TrackGauge.narrow,
        role: Role.GeneralPurpose,
        generation: Generation.first,
        gameplayMode: GameplayMode.simpliflied,
    },
    {
        name: "2-6-4 Bean Feast (Steam)",
        generation: Generation.second,
        maxSpeed: Speed.MilesPerHour(45),
        power: Power.Hp(400),
        mass: Mass.Tonne(22),
        te: TractiveEffort.Kn(42),
        length: 0.25,
        gauge: TrackGauge.narrow,
        role: Role.GeneralPurpose,
        gameplayMode: GameplayMode.simpliflied,
    },
    {
        name: "Pikel (Diesel)",
        generation: Generation.third,
        maxSpeed: Speed.MilesPerHour(55),
        power: Power.Hp(500),
        mass: Mass.Tonne(22),
        te: TractiveEffort.Kn(64),
        length: 0.25,
        gauge: TrackGauge.narrow,
        role: Role.GeneralPurpose,
        gameplayMode: GameplayMode.simpliflied,
    },
    {
        name: "Boar Cat (Diesel)",
        generation: Generation.fourth,
        maxSpeed: Speed.MilesPerHour(65),
        power: Power.Hp(600),
        mass: Mass.Tonne(23),
        te: TractiveEffort.Kn(67),
        length: 0.25,
        gauge: TrackGauge.narrow,
        role: Role.GeneralPurpose,
        gameplayMode: GameplayMode.simpliflied,
    },

    {
        name: "0-4-4-0 Thor (Steam)",
        generation: Generation.first,
        maxSpeed: Speed.MilesPerHour(45),
        power: Power.Hp(600),
        mass: Mass.Tonne(30),
        te: TractiveEffort.Kn(88),
        length: 0.375,
        gauge: TrackGauge.narrow,
        role: Role.GeneralPurpose,
        gameplayMode: GameplayMode.simpliflied,
    },
    {
        name: "0-4-4-0 Thor (Steam)",
        generation: Generation.second,
        maxSpeed: Speed.MilesPerHour(45),
        power: Power.Hp(600),
        mass: Mass.Tonne(30),
        te: TractiveEffort.Kn(88),
        length: 0.375,
        gauge: TrackGauge.narrow,
        role: Role.GeneralPurpose,
        gameplayMode: GameplayMode.simpliflied,
    },
    {
        name: "Gargouille (Diesel)",
        generation: Generation.third,
        maxSpeed: Speed.MilesPerHour(55),
        power: Power.Hp(750),
        mass: Mass.Tonne(30),
        te: TractiveEffort.Kn(88),
        length: 0.375,
        gauge: TrackGauge.narrow,
        role: Role.GeneralPurpose,
        gameplayMode: GameplayMode.simpliflied,
    },
    {
        name: "Maximillian (Diesel)",
        generation: Generation.fourth,
        maxSpeed: Speed.MilesPerHour(65),
        power: Power.Hp(900),
        mass: Mass.Tonne(31),
        te: TractiveEffort.Kn(91),
        length: 0.375,
        gauge: TrackGauge.narrow,
        role: Role.GeneralPurpose,
        gameplayMode: GameplayMode.simpliflied,
    },


    {
        name: "0-6-0+0-6-0 Keen (Steam)",
        role: Role.HeavyFreightJoker,
        generation: Generation.third,
        maxSpeed: Speed.MilesPerHour(60),
        power: Power.Hp(1800),
        mass: Mass.Tonne(116),
        gauge: TrackGauge.standard,
        te: TractiveEffort.Kn(341),
        length: 0.5,
        gameplayMode: GameplayMode.full,
    },
    {
        name: "0-8-2 Yak (Steam)",
        role: Role.LightFreightJoker,
        generation: Generation.third,
        maxSpeed: Speed.MilesPerHour(60),
        power: Power.Hp(1000),
        mass: Mass.Tonne(70),
        gauge: TrackGauge.standard,
        te: TractiveEffort.Kn(257),
        length: 0.5,
        gameplayMode: GameplayMode.full,
    },
    {
        name: "Dynamo (Electric)",
        role: Role.GeneralPurposeExpressJoker,
        generation: Generation.third,
        maxSpeed: Speed.MilesPerHour(90),
        power: Power.Hp(1800),
        mass: Mass.Tonne(92),
        gauge: TrackGauge.electric,
        te: TractiveEffort.Kn(271),
        length: 0.5,
        gameplayMode: GameplayMode.full,
    },
    {
        name: "Dryth (Electric)",
        role: Role.UltraHeavyFreightJoker,
        generation: Generation.third,
        maxSpeed: Speed.MilesPerHour(75),
        power: Power.Hp(2900),
        mass: Mass.Tonne(140),
        gauge: TrackGauge.electric,
        te: TractiveEffort.Kn(412),
        length: 0.5,
        gameplayMode: GameplayMode.full,
    },
    {
        name: "Maelstrom (Diesel)",
        role: Role.GeneralPurposeExpressJoker,
        generation: Generation.fourth,
        maxSpeed: Speed.MilesPerHour(75),
        power: Power.Hp(2200),
        mass: Mass.Tonne(115),
        gauge: TrackGauge.standard,
        te: TractiveEffort.Kn(338),
        length: 0.5,
        gameplayMode: GameplayMode.full,
    },
    {
        name: "Trojan (Diesel)",
        role: Role.FreightJoker,
        generation: Generation.fourth,
        maxSpeed: Speed.MilesPerHour(75),
        power: Power.Hp(1700),
        mass: Mass.Tonne(95),
        gauge: TrackGauge.standard,
        te: TractiveEffort.Kn(466),
        length: 0.5,
        gameplayMode: GameplayMode.full,
    },
    {
        name: "Lion (Diesel)",
        role: Role.SuperHeavyFreightJoker,
        generation: Generation.fourth,
        maxSpeed: Speed.MilesPerHour(75),
        power: Power.Hp(2950),
        mass: Mass.Tonne(95),
        gauge: TrackGauge.standard,
        te: TractiveEffort.Kn(176),
        length: 0.5,
        gameplayMode: GameplayMode.full,
    },
    {
        name: "Tincans (Electric)",
        role: Role.FreightJoker,
        generation: Generation.fifth,
        maxSpeed: Speed.MilesPerHour(87),
        power: Power.Hp(6200),
        mass: Mass.Tonne(140),
        gauge: TrackGauge.electric,
        te: TractiveEffort.Kn(466),
        length: 0.5,
        gameplayMode: GameplayMode.full,
    },

    {
        name: "Doineann (Diesel)",
        role: Role.HeavyFreight,
        generation: Generation.fourth,
        maxSpeed: Speed.MilesPerHour(87),
        power: Power.Hp(2750),
        mass: Mass.Tonne(87),
        gauge: TrackGauge.standard,
        te: TractiveEffort.Kn(324),
        length: 0.5,
        gameplayMode: GameplayMode.full,
    },
    {
        name: "Resistance (Electric)",
        role: Role.UltraHeavyFreightJoker,
        generation: Generation.fifth,
        maxSpeed: Speed.MilesPerHour(87),
        power: Power.Hp(5200),
        mass: Mass.Tonne(95),
        gauge: TrackGauge.electric,
        te: TractiveEffort.Kn(468),
        length: 0.5,
        gameplayMode: GameplayMode.full,
    },
    {
        name: "Centaur (Diesel)",
        role: Role.FreightJoker,
        generation: Generation.fifth,
        maxSpeed: Speed.MilesPerHour(87),
        power: Power.Hp(2000),
        mass: Mass.Tonne(120),
        gauge: TrackGauge.standard,
        te: TractiveEffort.Kn(390),
        length: 0.5,
        gameplayMode: GameplayMode.full,
    },
    {
        name: "General Endeavour (Diesel)",
        role: Role.LightFreightJoker,
        generation: Generation.fifth,
        maxSpeed: Speed.MilesPerHour(87),
        power: Power.Hp(1300),
        mass: Mass.Tonne(95),
        gauge: TrackGauge.standard,
        te: TractiveEffort.Kn(257),
        length: 0.5,
        gameplayMode: GameplayMode.full,
    },
    {
        name: "Constance (Diesel)",
        role: Role.FreightJoker,
        generation: Generation.sixth,
        maxSpeed: Speed.MilesPerHour(125),
        power: Power.Hp(3600),
        mass: Mass.Tonne(95),
        gauge: TrackGauge.standard,
        te: TractiveEffort.Kn(257),
        length: 0.5,
        gameplayMode: GameplayMode.full,
    },
    {
        name: "Constance (Electric)",
        role: Role.FreightJoker,
        generation: Generation.sixth,
        maxSpeed: Speed.MilesPerHour(125),
        power: Power.Hp(3600),
        mass: Mass.Tonne(95),
        gauge: TrackGauge.electric,
        te: TractiveEffort.Kn(280),
        length: 0.5,
        gameplayMode: GameplayMode.full,
    },
];

export const allEnginesVanilla = [
    {
        name: "Kirby Paul Tank (Steam) 1925",
        // units on page use Metric Tonne, not Ton (even though mph and hp are used). wtf
        mass: Mass.Tonne(47),
        maxSpeed: Speed.MilesPerHour(40),
        power: Power.Hp(300),
        te: TractiveEffort.Kn(137),
        length: 0.5,
        gauge: TrackGaugeVanilla.normal,
        climate: Climate.temperate,
        generation: Generation.first
    },
    {
        name: "Chaney 'Jubilee' (Steam) 1934",
        mass: Mass.Tonne(131),
        maxSpeed: Speed.MilesPerHour(70),
        power: Power.Hp(1000),
        te: TractiveEffort.Kn(381),
        length: 0.5,
        gauge: TrackGaugeVanilla.normal,
        climate: Climate.temperate,
        generation: Generation.first
    },
    {
        name: "Ginzu 'A4' (Steam) 1935",
        mass: Mass.Tonne(162),
        maxSpeed: Speed.MilesPerHour(80),
        power: Power.Hp(1200),
        te: TractiveEffort.Kn(471),
        length: 0.5,
        gauge: TrackGaugeVanilla.normal,
        climate: Climate.temperate,
        generation: Generation.first
    },

    {
        name: "SH '8P' (Steam) 1954",
        mass: Mass.Tonne(170),
        maxSpeed: Speed.MilesPerHour(90),
        power: Power.Hp(1600),
        te: TractiveEffort.Kn(495),
        length: 0.5,
        gauge: TrackGaugeVanilla.normal,
        climate: Climate.temperate,
        generation: Generation.second
    },
    {
        name: "Manely-Morel DMU (Diesel) 1957",
        mass: Mass.Tonne(32),
        maxSpeed: Speed.MilesPerHour(70),
        power: Power.Hp(600),
        te: TractiveEffort.Kn(186),
        length: 1,
        gauge: TrackGaugeVanilla.normal,
        climate: Climate.temperate,
        generation: Generation.second
    },
    {
        name: "UU '37' (Diesel) 1959",
        mass: Mass.Tonne(101),
        maxSpeed: Speed.MilesPerHour(90),
        power: Power.Hp(1750),
        te: TractiveEffort.Kn(294),
        length: 0.5,
        gauge: TrackGaugeVanilla.normal,
        climate: Climate.temperate,
        generation: Generation.second
    },
    { // Chaney upgrade
        name: "SH/Hendry '25' (Diesel) 1962",
        mass: Mass.Tonne(72),
        maxSpeed: Speed.MilesPerHour(80),
        power: Power.Hp(1250),
        te: TractiveEffort.Kn(209),
        length: 0.5,
        gauge: TrackGaugeVanilla.normal,
        climate: Climate.temperate,
        generation: Generation.second
    },
    {
        name: "Floss '47' (Diesel) 1962",
        mass: Mass.Tonne(112),
        maxSpeed: Speed.MilesPerHour(100),
        power: Power.Hp(2580),
        te: TractiveEffort.Kn(326),
        length: 0.5,
        gauge: TrackGaugeVanilla.normal,
        climate: Climate.temperate,
        generation: Generation.second
    },
    { // replaces Floss '47'/ direct upgrade
        name: "SH '30' (Electric) 1965",
        mass: Mass.Tonne(84),
        maxSpeed: Speed.MilesPerHour(100),
        power: Power.Hp(3600),
        te: TractiveEffort.Kn(244),
        length: 0.5,
        gauge: TrackGaugeVanilla.electric,
        climate: Climate.temperate,
        generation: Generation.second
    },

    { // SH '30' upgrade
        name: "SH '40' (Electric) 1973",
        mass: Mass.Tonne(82),
        maxSpeed: Speed.MilesPerHour(110),
        power: Power.Hp(5000),
        te: TractiveEffort.Kn(239),
        length: 0.5,
        gauge: TrackGaugeVanilla.electric,
        climate: Climate.temperate,
        generation: Generation.third
    },
    {
        name: "SH '125' (Diesel) 1978",
        mass: Mass.Tonne(70),
        maxSpeed: Speed.MilesPerHour(125),
        power: Power.Hp(4500),
        te: TractiveEffort.Kn(407),
        length: 1,
        gauge: TrackGaugeVanilla.normal,
        climate: Climate.temperate,
        generation: Generation.third
    },
    { // replaces DMU
        name: "Dash (Diesel) 1984",
        mass: Mass.Tonne(38),
        maxSpeed: Speed.MilesPerHour(75),
        power: Power.Hp(700),
        te: TractiveEffort.Kn(221),
        length: 1,
        gauge: TrackGaugeVanilla.normal,
        climate: Climate.temperate,
        generation: Generation.third
    },
    {
        name: "T.I.M. (Electric) 1984",
        mass: Mass.Tonne(90),
        maxSpeed: Speed.MilesPerHour(150),
        power: Power.Hp(7000),
        te: TractiveEffort.Kn(524),
        length: 1,
        gauge: TrackGaugeVanilla.electric,
        climate: Climate.temperate,
        generation: Generation.third
    },

    {
        name: "AsiaStar (Electric) 1992",
        mass: Mass.Tonne(94),
        maxSpeed: Speed.MilesPerHour(165),
        power: Power.Hp(8000),
        te: TractiveEffort.Kn(553),
        length: 1,
        gauge: TrackGaugeVanilla.electric,
        climate: Climate.temperate,
        generation: Generation.fourth
    },
    {
        name: "X2001 (Monorail) 1999",
        mass: Mass.Tonne(95),
        maxSpeed: Speed.MilesPerHour(190),
        power: Power.Hp(9000),
        te: TractiveEffort.Kn(276),
        length: 0.5,
        gauge: TrackGaugeVanilla.monorail,
        climate: Climate.temperate,
        generation: Generation.fourth
    },
    {
        name: "Millennium Z1 (Monorail) 2005",
        mass: Mass.Tonne(179),
        maxSpeed: Speed.MilesPerHour(210),
        power: Power.Hp(10000),
        te: TractiveEffort.Kn(495),
        length: 1,
        gauge: TrackGaugeVanilla.monorail,
        climate: Climate.temperate,
        generation: Generation.fourth
    },

    {
        name: "Lev1 'Leviathan' (MagLev) 2021",
        mass: Mass.Tonne(105),
        maxSpeed: Speed.MilesPerHour(251),
        power: Power.Hp(10000),
        te: TractiveEffort.Kn(1000), // TE not applicable
        length: 0.5,
        gauge: TrackGaugeVanilla.maglev,
        climate: Climate.temperate,
        generation: Generation.fifth
    },
    {
        name: "Lev2 'Cyclops' (MagLev) 2028",
        mass: Mass.Tonne(120),
        maxSpeed: Speed.MilesPerHour(281),
        power: Power.Hp(12000),
        te: TractiveEffort.Kn(1000), // TE not applicable
        length: 0.5,
        gauge: TrackGaugeVanilla.maglev,
        climate: Climate.temperate,
        generation: Generation.fifth
    },

    {
        name: "Lev3 'Pegasus' (MagLev) 2035",
        mass: Mass.Tonne(130),
        maxSpeed: Speed.MilesPerHour(300),
        power: Power.Hp(15000),
        te: TractiveEffort.Kn(1000), // TE not applicable
        length: 0.5,
        gauge: TrackGaugeVanilla.maglev,
        climate: Climate.temperate,
        generation: Generation.sixth
    },
    {
        name: "Lev4 'Chimaera' (MagLev) 2037",
        mass: Mass.Tonne(300),
        maxSpeed: Speed.MilesPerHour(402),
        power: Power.Hp(20000),
        te: TractiveEffort.Kn(1000), // TE not applicable
        length: 1,
        gauge: TrackGaugeVanilla.maglev,
        climate: Climate.temperate,
        generation: Generation.sixth
    },
];
